Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.AV1VideoExtension_8wekyb3d8bbwe.x64.appx      -LicensePath licenses\Microsoft.AV1VideoExtension_8wekyb3d8bbwe.x64.xml   
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.D3DMappingLayers_8wekyb3d8bbwe.x64.appx       -LicensePath licenses\Microsoft.D3DMappingLayers_8wekyb3d8bbwe.x64.xml    
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle  -LicensePath licenses\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.xml     -DependencyPackagePath "packages\Microsoft.UI.Xaml.x64.2.7.appx","packages\Microsoft.VCLibs.x64.14.00.UWPDesktop.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.HEIFImageExtension_8wekyb3d8bbwe.x64.appx     -LicensePath licenses\Microsoft.HEIFImageExtension_8wekyb3d8bbwe.x64.xml  
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.HEVCVideoExtension_8wekyb3d8bbwe.x64.appx     -LicensePath licenses\Microsoft.HEVCVideoExtension_8wekyb3d8bbwe.x64.xml  -DependencyPackagePath "packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.MPEG2VideoExtension_8wekyb3d8bbwe.x64.appx    -LicensePath licenses\Microsoft.MPEG2VideoExtension_8wekyb3d8bbwe.x64.xml 
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.RawImageExtension_8wekyb3d8bbwe.appxbundle    -LicensePath licenses\Microsoft.RawImageExtension_8wekyb3d8bbwe.xml       
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.ScreenSketch_8wekyb3d8bbwe.msixbundle         -LicensePath licenses\Microsoft.ScreenSketch_8wekyb3d8bbwe.xml            -DependencyPackagePath "packages\Microsoft.UI.Xaml.x64.2.7.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.SecHealthUI_8wekyb3d8bbwe.x64.appx            -LicensePath licenses\Microsoft.SecHealthUI_8wekyb3d8bbwe.x64.xml         -DependencyPackagePath "packages\Microsoft.UI.Xaml.x64.2.4.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.VP9VideoExtensions_8wekyb3d8bbwe.x64.appx     -LicensePath licenses\Microsoft.VP9VideoExtensions_8wekyb3d8bbwe.x64.xml  
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.WebMediaExtensions_8wekyb3d8bbwe.appxbundle   -LicensePath licenses\Microsoft.WebMediaExtensions_8wekyb3d8bbwe.xml      -DependencyPackagePath "packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.WebpImageExtension_8wekyb3d8bbwe.x64.appx     -LicensePath licenses\Microsoft.WebpImageExtension_8wekyb3d8bbwe.x64.xml  
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.Windows.Photos_8wekyb3d8bbwe.appxbundle       -LicensePath licenses\Microsoft.Windows.Photos_8wekyb3d8bbwe.xml          -DependencyPackagePath "packages\Microsoft.NET.Native.Framework.x64.2.2.appx","packages\Microsoft.NET.Native.Runtime.x64.2.2.appx","packages\Microsoft.UI.Xaml.x64.2.4.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.WindowsCalculator_8wekyb3d8bbwe.appxbundle    -LicensePath licenses\Microsoft.WindowsCalculator_8wekyb3d8bbwe.xml       -DependencyPackagePath "packages\Microsoft.UI.Xaml.x64.2.4.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.WindowsCamera_8wekyb3d8bbwe.msixbundle        -LicensePath licenses\Microsoft.WindowsCamera_8wekyb3d8bbwe.xml           -DependencyPackagePath "packages\Microsoft.NET.Native.Framework.x64.2.2.appx","packages\Microsoft.NET.Native.Runtime.x64.2.2.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.WindowsNotepad_8wekyb3d8bbwe.msixbundle       -LicensePath licenses\Microsoft.WindowsNotepad_8wekyb3d8bbwe.xml          -DependencyPackagePath "packages\Microsoft.UI.Xaml.x64.2.7.appx","packages\Microsoft.VCLibs.x64.14.00.appx","packages\Microsoft.VCLibs.x64.14.00.UWPDesktop.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe.appxbundle -LicensePath licenses\Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe.xml    -DependencyPackagePath "packages\Microsoft.UI.Xaml.x64.2.3.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.WindowsStore_8wekyb3d8bbwe.msixbundle         -LicensePath licenses\Microsoft.WindowsStore_8wekyb3d8bbwe.xml            -DependencyPackagePath "packages\Microsoft.NET.Native.Framework.x64.2.2.appx","packages\Microsoft.NET.Native.Runtime.x64.2.2.appx","packages\Microsoft.UI.Xaml.x64.2.7.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe.msixbundle      -LicensePath licenses\Microsoft.WindowsTerminal_8wekyb3d8bbwe.xml         -DependencyPackagePath "packages\Microsoft.UI.Xaml.x64.2.7.appx","packages\Microsoft.VCLibs.x64.14.00.UWPDesktop.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.ZuneMusic_8wekyb3d8bbwe.msixbundle            -LicensePath licenses\Microsoft.ZuneMusic_8wekyb3d8bbwe.xml               -DependencyPackagePath "packages\Microsoft.NET.Native.Framework.x64.2.2.appx","packages\Microsoft.NET.Native.Runtime.x64.2.2.appx","packages\Microsoft.UI.Xaml.x64.2.7.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
Add-ProvisionedAppPackage -Path W:\ -PackagePath packages\Microsoft.ZuneVideo_8wekyb3d8bbwe.appxbundle            -LicensePath licenses\Microsoft.ZuneVideo_8wekyb3d8bbwe.xml               -DependencyPackagePath "packages\Microsoft.UI.Xaml.x64.2.7.appx","packages\Microsoft.VCLibs.x64.14.00.appx"
