cd ..\Inbox_Apps
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.AV1VideoExtension_8wekyb3d8bbwe.x64.appx     -LicensePath Microsoft.AV1VideoExtension_8wekyb3d8bbwe.x64.xml   
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -LicensePath Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.xml     -DependencyPackagePath Microsoft.UI.Xaml.x64.2.7.appx,Microsoft.VCLibs.x64.14.00.UWPDesktop.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.HEIFImageExtension_8wekyb3d8bbwe.x64.appx    -LicensePath Microsoft.HEIFImageExtension_8wekyb3d8bbwe.x64.xml  
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.HEVCVideoExtension_8wekyb3d8bbwe.x64.appx    -LicensePath Microsoft.HEVCVideoExtension_8wekyb3d8bbwe.x64.xml  -DependencyPackagePath Microsoft.VCLibs.x64.14.00.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.MPEG2VideoExtension_8wekyb3d8bbwe.x64.appx   -LicensePath Microsoft.MPEG2VideoExtension_8wekyb3d8bbwe.x64.xml 
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.RawImageExtension_8wekyb3d8bbwe.appxbundle   -LicensePath Microsoft.RawImageExtension_8wekyb3d8bbwe.xml       
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.ScreenSketch_8wekyb3d8bbwe.msixbundle        -LicensePath Microsoft.ScreenSketch_8wekyb3d8bbwe.xml            -DependencyPackagePath Microsoft.UI.Xaml.x64.2.7.appx,Microsoft.VCLibs.x64.14.00.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.SecHealthUI_8wekyb3d8bbwe.x64.appx           -LicensePath Microsoft.SecHealthUI_8wekyb3d8bbwe.x64.xml         -DependencyPackagePath Microsoft.UI.Xaml.x64.2.4.appx,Microsoft.VCLibs.x64.14.00.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.VP9VideoExtensions_8wekyb3d8bbwe.x64.appx    -LicensePath Microsoft.VP9VideoExtensions_8wekyb3d8bbwe.x64.xml  
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.WebMediaExtensions_8wekyb3d8bbwe.appxbundle  -LicensePath Microsoft.WebMediaExtensions_8wekyb3d8bbwe.xml      -DependencyPackagePath Microsoft.VCLibs.x64.14.00.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.WebpImageExtension_8wekyb3d8bbwe.x64.appx    -LicensePath Microsoft.WebpImageExtension_8wekyb3d8bbwe.x64.xml  
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.Windows.Photos_8wekyb3d8bbwe.appxbundle      -LicensePath Microsoft.Windows.Photos_8wekyb3d8bbwe.xml          -DependencyPackagePath Microsoft.NET.Native.Framework.x64.2.2.appx,Microsoft.NET.Native.Runtime.x64.2.2.appx,Microsoft.UI.Xaml.x64.2.4.appx,Microsoft.VCLibs.x64.14.00.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.WindowsCalculator_8wekyb3d8bbwe.appxbundle   -LicensePath Microsoft.WindowsCalculator_8wekyb3d8bbwe.xml       -DependencyPackagePath Microsoft.UI.Xaml.x64.2.4.appx,Microsoft.VCLibs.x64.14.00.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.WindowsNotepad_8wekyb3d8bbwe.msixbundle      -LicensePath Microsoft.WindowsNotepad_8wekyb3d8bbwe.xml          -DependencyPackagePath Microsoft.UI.Xaml.x64.2.7.appx,Microsoft.VCLibs.x64.14.00.appx,Microsoft.VCLibs.x64.14.00.UWPDesktop.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.WindowsStore_8wekyb3d8bbwe.msixbundle        -LicensePath Microsoft.WindowsStore_8wekyb3d8bbwe.xml            -DependencyPackagePath Microsoft.NET.Native.Framework.x64.2.2.appx,Microsoft.NET.Native.Runtime.x64.2.2.appx,Microsoft.UI.Xaml.x64.2.7.appx,Microsoft.VCLibs.x64.14.00.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.WindowsTerminal_8wekyb3d8bbwe.msixbundle     -LicensePath Microsoft.WindowsTerminal_8wekyb3d8bbwe.xml         -DependencyPackagePath Microsoft.UI.Xaml.x64.2.7.appx,Microsoft.VCLibs.x64.14.00.UWPDesktop.appx
Add-ProvisionedAppPackage -Online -PackagePath Microsoft.ZuneMusic_8wekyb3d8bbwe.msixbundle           -LicensePath Microsoft.ZuneMusic_8wekyb3d8bbwe.xml               -DependencyPackagePath Microsoft.NET.Native.Framework.x64.2.2.appx,Microsoft.NET.Native.Runtime.x64.2.2.appx,Microsoft.UI.Xaml.x64.2.7.appx,Microsoft.VCLibs.x64.14.00.appx
